apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coredog.fullname" . }}
  labels:
    {{- include "coredog.labels" . | nindent 4 }}
data:
  coredog.yaml: {{ .Values.config.coredog | quote }}
  watcher.yaml: {{ .Values.config.coredog | quote }}
