{{- if .Values.watcher.kubeLookup }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredog-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredog-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredog-reader
subjects:
- kind: ServiceAccount
  name: coredog
  namespace: coredog-system
{{- end }}

