apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "coredog.fullname" . }}-watcher
  labels:
    {{- include "coredog.watcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "coredog.watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coredog.watcher.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "coredog.fullname" . }}
      # Keep chart minimal: advanced pod settings can be added when needed
      containers:
      - name: watcher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: {{ .Values.corefileVolume.name }}
          mountPath: /corefile
        args: ["./coredog","watcher"]
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_LOOKUP
          value: "{{ .Values.watcher.kubeLookup | toString }}"
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "coredog.fullname" . }}
        - name: {{ .Values.corefileVolume.name }}
          hostPath:
            path: {{ .Values.corefileVolume.hostPath.path }}
            type: {{ .Values.corefileVolume.hostPath.type }}