name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3

      - name: Lint chart
        run: |
          helm lint charts

      - name: Package chart
        run: |
          mkdir -p dist
          helm package charts --destination dist

      - name: Generate index.yaml
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          URL="https://${OWNER}.github.io/${REPO}"
          helm repo index dist --url "$URL"

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          force_orphan: true


